apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-cicd-demo
    component: zxq-devops
    tier: backend
  name: k8s-cicd-demo
  namespace: devops-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: k8s-cicd-demo
      component: zxq-devops
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-cicd-demo
        component: zxq-devops
        tier: backend
    spec:
      #imagePullSecrets:
      #  - name: k8s-cicd-demo
      containers:
        - name: k8s-cicd-demo
          image: registry.cn-hangzhou.aliyuncs.com/aerith/k8s-cicd-demo:v1
          #command: ["/app/main.exe"]
          #readinessProbe:
           # httpGet:
           #   path: /users
            #  port: 8080
            #timeoutSeconds: 10
            #failureThreshold: 30
            #periodSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 400m
              memory: 600Mi
            requests:
              cpu: 200m
              memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-cicd-demo
    component: zxq-devops
  name: k8s-cicd-demo
  namespace: devops-test
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8s-cicd-demo
    component: zxq-devops
    tier: backend
  sessionAffinity: None
  type: NodePort

