apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-cicd-demo
    component: zxq-devops
    tier: backend
  name: k8s-cicd-demo
  namespace: devops-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: k8s-cicd-demo
      component: zxq-devops
      tier: backend
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 100%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: k8s-cicd-demo
        component: zxq-devops
        tier: backend
    spec:
      #imagePullSecrets:
      #  - name: k8s-cicd-demo
      containers:
        - name: k8s-cicd-demo
          image: registry.cn-hangzhou.aliyuncs.com/aerith/k8s-cicd-demo:v1
          #command: ["/bin/sh", "-c", "sleep 100000;" ]
          command: ["/devops-test/main.go"]
          imagePullPolicy: Always
          #readinessProbe:
           # httpGet:
           #   path: /users
            #  port: 8080
            #timeoutSeconds: 10
            #failureThreshold: 30
            #periodSeconds: 5
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 300m
              memory: 600Mi
            requests:
              cpu: 100m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-cicd-demo
    component: zxq-devops
  name: k8s-cicd-demo
  namespace: devops-test
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: k8s-cicd-demo
    component: zxq-devops
    tier: backend
  sessionAffinity: None
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: k8s-cicd-demo
  annotations:
    kubernetes.io/ingress.class: "nginx"
  namespace: devops-test
spec:
  rules:
    - host: demo.cicd.com
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: k8s-cicd-demo
                port:
                  number: 8080
            path: /
